<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>WOWSlider generated by WOWSlider.com</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="WOW Slider, slider html, jquery slider" />
        <meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
        <!-- Start WOWSlider.com HEAD section -->
        <!-- <link rel="stylesheet" type="text/css" href="engine1/style.css" /> -->
        <?php echo $this->Html->css("engine1/style"); ?> 

        <script type="text/javascript" src="engine1/jquery.js"></script>
        <?php echo $this->Html->script("engine1/jquery"); ?> 

        <!-- End WOWSlider.com HEAD section -->
    </head>
    <body style="background-color:#d7d7d7">
        <!-- Start WOWSlider.com BODY section -->
        <div id="wowslider-container1">
            <div class="ws_images">
                <ul>

                    <?php
                    $i = 0;
                    foreach ($images as $image) {
                        $xhtml = '<li>';
                        $url = "slide/" . $image['Image']['name'];
                        $id = "wows1_" . $i;
                        $alt = $place['Place']['name'];
                        $xhtml .= $this->Html->image($url, array("alt" => $alt, "id" => $id, "title" => ""));
                        $i++;
                        echo $xhtml;
                    }
                    ?>
                    
                </ul></div>
            <span class="wsl"><a href="http://wowslider.net">css slider</a> by WOWSlider.com v5.5</span>
            <div class="ws_shadow"></div>
        </div>

        <?php echo $this->Html->script("engine1/wowslider"); ?> 
        <?php echo $this->Html->script("engine1/script"); ?> 


    </body>
</html>